"""Retain student number ownership

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-14 01:08:01.049879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_number_claim',
    sa.Column('student_number', sa.String(length=9), nullable=False),
    sa.Column('student_pk', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_pk'], ['student.id'], ),
    sa.PrimaryKeyConstraint('student_number')
    )
    with op.batch_alter_table('student_number_claim', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_number_claim_student_pk'), ['student_pk'], unique=False)

    op.execute('INSERT INTO student_number_claim (student_number, student_pk) SELECT student_number, id FROM student')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_number_claim', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_number_claim_student_pk'))

    op.drop_table('student_number_claim')
    # ### end Alembic commands ###
